### ISSUE TITLE
Error on delete documents (deleteByQuery)

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/sdk-javascript#157]
Using kuzzle on develop (RC8) and latest SDK

an error occurred when calling: 
`KuzzleDataCollection.deleteDocument({}, callback);`
with message: 
`Error: deleteByQuery must specify a body attribute "query"`

https://github.com/kuzzleio/sdk-javascript/blob/develop/src/kuzzleDataCollection.js#L272
replacing `data.body = arg;` by `data.query = arg;` seem to fixes the issue
but we have to replace our call by: 
`KuzzleDataCollection.deleteDocument({query: {}}, callback);`

**Comment by ballinette** [comment]
moved to https://github.com/kuzzleio/sdk/issues/4
