### ISSUE TITLE
Implement get*Mapping and set*Mapping

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/sdk-javascript#171]
Linked to https://github.com/kuzzleio/kuzzle/pull/624

**Comment by ballinette** [comment]
Actually, there is no consensus within the team if we implement these features or not within the SDK.

We can also use directly `query` to call these actions.

So waiting a decision about this.

**Comment by ballinette** [comment]
Moved to https://github.com/kuzzleio/sdk/issues/7
