### ISSUE TITLE
Suggestion : Room.js should be independant of Collection

### ISSUE THREAD

**Issue by neolas** [kuzzleio/sdk-javascript#174]
Hello,

I'm implementing a custom Plugin to manage specific realtime notifications ( filters are built plugin side based on policies, user account and other conditions).

On 3.0.1 branch, I must redefine a new class to only change : 
- calls to collection.buildQueryArgs
- parameters KuzzleDataCollection of constructor (I specify kuzzle object and query Args controller/action/collection(not requires)/index(not required) )

I think it could be really interesting to make this class more independant :) 

Cheers,

**Comment by ballinette** [comment]
moved to https://github.com/kuzzleio/sdk/issues/8
