### ISSUE TITLE
Collection.fetchAllDocuments output format

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/sdk-javascript#203]
According to the [SDK documentation](http://docs.kuzzle.io/sdk-reference/#fetchalldocuments), the output of `collection.fetchAllDocuments` should has the form
```js
{
  total: XX,
  documents: [ doc1, doc2, ... ]
}
```

The actual output is just the documents array.

I suppose we have 2 options:
1. leave the output format as-is and fix the documentation
2. correct the output to match format expected in the doc.

Each solution has its pros and cons, and need to be discussed IMO

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/kuzzle-sdk #23](https://github.com/kuzzleio/kuzzle-sdk/issues/23) via [**ZenHub**](https://www.zenhub.com/)
