### ISSUE TITLE
FetchAllDocuments is using pagination

### ISSUE THREAD

**Issue by jenow** [kuzzleio/sdk-javascript#207]
FetchAllDocuments is using pagination but should return ALL documents.

**Comment by benoitvidis** [comment]
linked to https://github.com/kuzzleio/sdk-javascript/issues/203

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/kuzzle-sdk #22](https://github.com/kuzzleio/kuzzle-sdk/issues/22) via [**ZenHub**](https://www.zenhub.com/)
