### ISSUE TITLE
add a debug mode

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/sdk-javascript#276]
@scottinet commented on [Wed Jan 17 2018](https://github.com/kuzzleio/kuzzle-sdk/issues/66)

add a debug option to the kuzzle sdk constructor, printing to the standard output the changes in the network layer, and the requests/responses handled by the query central function

**Comment by ballinette** [comment]
refs #/125

**Comment by Yoann-Abbes** [comment]
Obsolete, won't do
