### ISSUE TITLE
It would be nice to have a connection timeout settings in Kuzzle constructor

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/sdk-javascript#277]
@etrousset commented on [Tue Dec 19 2017](https://github.com/kuzzleio/kuzzle-sdk/issues/64)

When connecting to kuzzle, there is currently no way to set a connection time out. 
 It would be nice to be able to change the default value of around 1min

**Comment by Yoann-Abbes** [comment]
Will do more generic https://github.com/kuzzleio/kuzzle/issues/1659

**Comment by Yoann-Abbes** [comment]
Will do https://github.com/kuzzleio/sdk-javascript/issues/555
