### ISSUE TITLE
Documentation or code is broken on Collection.document()

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/sdk-javascript#303]
The doc (https://docs.kuzzle.io/sdk-reference/collection/document) says when I use the `document` function, the ID is optional and returns a KuzzleDocument.

When creating a document, I want to let Kuzzle to generate the ID, so following the documentation, I do like this : 

`kuzzle.collection().document({some: 'content})`

I have a KuzzleDocument. Then when I call `.save()`, I have an error because the ID is undefined, since `.save` is calling `createOrReplace` without any ID

## Expected Behavior

Since the ID is optionnal in `.document` method, the ID should be autogenerated allowing to perform a .save() OR the ID parameter should not be optional

## Current Behavior

Impossible to do a `Kuzzle.collection.document({content: 'some'}).save()` with a new document

## Possible Solution

Autogenerate ID for new document OR make ID parameter mandatory

**Comment by Aschen** [comment]
Hi @Tyki, thanks for the feedback !
`document()` should definitively call `create` instead of `createOrReplace` when the id is not provided.
