### ISSUE TITLE
[Security Controller] missing  or bad signature methods

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/sdk-javascript#307]
* missing methods in `Security` controller:
  * [createRestrictedUser](https://docs.kuzzle.io/api-documentation/controller-security/create-restricted-user) 

* get*Mapping methods should return `response.result.mapping` (ot throw an error if no mapping found):
  * getProfileMapping
  * getRoleMapping
  * getUserMapping

**Comment by scottinet** [comment]
Fixed a long time ago
