### ISSUE TITLE
[createDocument] Error while creating a document with numeric Identifier

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/sdk-javascript#314]
A wired error is raised while creating a document with numeric Identifier

## Expected Behavior
* A `TypeError` should be thrown with appropriate error message
* maybe the type should be casted into string when it's possible (numeric values for instance)

## Current Behavior
Currently, theses errors are thrown:
* `Error: Attribute body must be of type "object"` with `collection.createDocumentPromise(1, {foo: 'bar'})` call
* `TypeError: cb is not a function`  with `collection.createDocumentPromise(1, {foo: 'bar'}, {ifExist: 'replace'})` call

## Possible Solution
Type checking before sending request ?

## Steps to Reproduce
1. Run this with latest stable kuzzle-sdk version (5.0.13)

```es6
const Kuzzle = require('kuzzle-sdk')

async function main () {
  let kuzzle = new Kuzzle('localhost', { defaultIndex: 'index' })
  let collection = kuzzle.collection('collection')

  try {
   // raise error
    await collection.createDocumentPromise(1, {foo: 'bar'}, {ifExist: 'replace'})
  }
  catch (error) {
    console.error(error)
    process.exit(1)
  }

  try {
   // works good
    await collection.createDocumentPromise('1', {foo: 'bar'}, {ifExist: 'replace'})
  }
  catch (error) {
    console.error(error)
    process.exit(1)
  }


  process.exit()
}

main()
```

**Comment by Aschen** [comment]
With the latest version of the SDK
```
const {
  Kuzzle,
  WebSocket
} = require('kuzzle-sdk');

const kuzzle = new Kuzzle(
  new WebSocket('kuzzle')
);

(async () => {
  try {
    await kuzzle.connect();
    await kuzzle.document.create('index', 'collection', { foo: 'bar' }, 42)
  } catch (error) {
    console.error(error)
  }
})()
```
will throw the following error: `Error: Attribute _id must be of type "string"`
