### ISSUE TITLE
Improvement suggestion for SDK V6 instantiation

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/sdk-javascript#321]
Hello,

**⚠️I'm very enthusiast about the new SDK6, so I would like to help and suggests some interrogations that maybe you didn't thought about, maybe you already :).**

Documentation on Kuzzle Client object seems inconsistent, sometimes it is written that `options` is required, sometimes not. Plus protocol specific code is passed to options.

I would like to present a pattern that can be nice to handle with such code structure and really nice for extensibility. This is heavily modular and allows to maximum extensibility which is I think your goal (support most protocol as possible).

# My suggestion

I think each protocol should contain his own configuration which is specific to himself. Also kuzzle client must own his own configuration.

We are ending up with something like this.

```ts
import { Kuzzle, HttpProtocol } from "kuzzle-sdk";

// The best pattern (my point of view)
const kuzzleClient = new KuzzleClient({
    protocol: new HttpProtocol({ host: "10.23.45.55" })
    // any non-protocol-specific kuzzle configuration.
});

// Another pattern which is a bit less extensible because we are using param and not a config object.
const protocol = new HttpProtocol({ host: "10.23.45.55" });
const kuzzleConfig = { /* ... */ };
const kuzzleClient = new KuzzleClient(protocol, kuzzleConfig);

// Kuzzle Config is truly optional here.
```

This pattern is very simple and many actors of the web are already implementing it, because it allows to keep as most as possible doors open to extensibility.

As an example you can check the [apollo-client](https://github.com/apollographql/apollo-client) which is a graphql-client with about 9000 stars today. They are implementing even separate package, which is probably over-engineered for our use case.

```ts
import { ApolloLink } from 'apollo-link';
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';

const client = new ApolloClient({
  link: new HttpLink({ uri: 'http://api.githunt.com/graphql' }),
  cache: new InMemoryCache()
});
```

That's all.

Let me know if you thought about this and thanks for considering my feedback.

Best regards,
Andréas

**Comment by stafyniaksacha** [comment]
In my case I prefer the middleware approach: `kuzzle.use(plugin)` 
Like used in Express, Vuejs, Koa, Metalsmith, ...

This can allow multiple plugins for kuzzle sdk:
```js
import { 
  Kuzzle, 
  AbstractProtocol, 
  AbstractController, 
  AbstractPipe 
} from "kuzzle-sdk";

class MyKuzzleProtocol extends AbstractProtocol
{
  // implement AbstractProtocol
}

class MyKuzzleController extends AbstractProtocol
{
  // implement AbstractProtocol
}

class MyKuzzlePipe extends AbstractPipe
{
  // implement AbstractPipe
}

const protocolOptions = {}
const controllerOptions = {}
const pipeOptions = {}

Kuzzle.use( new MyKuzzleProtocol( protocolOptions ) )
Kuzzle.use( new MyKuzzleController( controllerOptions ) )
Kuzzle.use( new MyKuzzlePipe( pipeOptions ) )

const kuzzle = new Kuzzle('my-custom-controller')
```

**Comment by ScreamZ** [comment]
@stafyniaksacha Why not, it has the advantage of allowing plugins loading order. As long as each object own his own configuration I'm confident.

**Comment by ScreamZ** [comment]
@benoitvidis @Aschen Any news about this ? (not tagged internally)

**Comment by Aschen** [comment]
As been implemented
