### ISSUE TITLE
[6.0.0-beta2] HTTP NetworkHandler does not work as expected

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/sdk-javascript#324]
I've tried to switch network handler in a working application using  websocket network handler, and every thing hangs up 

## Expected Behavior
The HTTP network handler should work like websoket one (without realtime)

## Current Behavior
At request creation time, `queryArgs` are populated with SDK default options which contains `undefined` or `null` values that are included in `queryArgs` as is. Kuzzle trait them as string.

## Steps to Reproduce
When we create a document like something:

```js 
await kuzzle.document.create(
  "index",
  "colection",
  null,
  awesomeDocument,
  {
    refresh: "wait_for"
  }
);
```
The document ID became `"null"`
The scroll parameter became `"undefined"`
etc ...

## Possible Solution
In `send` method on `networkWrapper/protocols/http.js`, but need to be tested

```diff
for (const key of Object.keys(data)) {
  const value = data[key];

  if (key === 'body') {
    payload.body = JSON.stringify(value);
  } else if (key === 'jwt') {
    payload.headers.authorization = 'Bearer ' + value;
  } else if (key === 'volatile') {
    payload.headers['x-kuzzle-volatile'] = JSON.stringify(value);
  } else if (payload.hasOwnProperty(key)) {
    payload[key] = value;
-  } else {
-    queryArgs[key] = value;
-  }
+  } else if (value !== undefined && value !== null) {
+    queryArgs[key] = value;
+  }
}
```

**Comment by Aschen** [comment]
Hello @stafyniaksacha, thanks for the feedback!

I didn't manage to reproduce your error, here you can see my code: https://gist.github.com/Aschen/6645445ab6d5608611f85e004fb4f1d9 
I run this snippet in the sdk-javascript folder locally

**Comment by stafyniaksacha** [comment]
I run you code and I get:
```
{ _index: 'index',
  _type: 'collection',
  _id: 'null',
  _version: 1,
  found: true,
  _source: 
   { hello: 'world',
     _kuzzle_info: 
      { author: '-1',
        createdAt: 1540739055056,
        updatedAt: null,
        updater: null,
        active: true,
        deletedAt: null } },
  _meta: 
   { author: '-1',
     createdAt: 1540739055056,
     updatedAt: null,
     updater: null,
     active: true,
     deletedAt: null } }
```

the problem is there: `_id: 'null'`
