### ISSUE TITLE
[6-dev] event listeners leak on protocol disconnect

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/sdk-javascript#356]
## Current Behavior
When a query is emitted by a protocol, an event listener is registered to handle the server answer (see [here in abstract protocol](https://github.com/kuzzleio/sdk-javascript/blob/6-dev/src/protocols/abstract/common.js))

The problem is that nothing discard pending, in memory, listeners when something wrong append with network

## Possible Solution
Once listeners should be cleaned when a disconnection occurred. 
It would be nice to let user to choose what to do at this point (replay request / silent discard / error request)

**Comment by Aschen** [comment]
Hi @stafyniaksacha, thanks for the feedback! It's very much appreciated.
We will address this bug soon

**Comment by Aschen** [comment]
FIxed by #424
