### ISSUE TITLE
[6-dev] discarded payload is treated as a discarded request

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/sdk-javascript#357]
## Expected Behavior
We can't distinguish between discarded requests and responses.
There is actually only on event `discarded` which is emitted when : 
- a _query_ is emitted when [a protocol is not connected](https://github.com/kuzzleio/sdk-javascript/blob/6-dev/src/protocols/abstract/common.js#L78)
- a non queuable _query_ is discarded [during queue registration](https://github.com/kuzzleio/sdk-javascript/blob/6-dev/src/Kuzzle.js#L405)
- **but also when a [_response_ is discarded](https://github.com/kuzzleio/sdk-javascript/blob/6-dev/src/protocols/websocket.js#L92)**

It would be nice to be able to manage both cases independently.

**Comment by Aschen** [comment]
Hi @stafyniaksacha, thanks for the feedback! It's very much appreciated.
We will address this bug soon
