### ISSUE TITLE
[6-dev] multiple Kuzzle.connect() calls result in unexpected behavior

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/sdk-javascript#358]
## Current Behavior
Consider this code: 
``` js
...
const {
  Kuzzle,
  WebSocket
} = require('kuzzle-sdk');

const kuzzle = new Kuzzle(
  new WebSocket('kuzzle')
);

kuzzle.on('connected', _ => console.log('connected'));
kuzzle.on('reconnected', _ => console.log('reconnected'));

kuzzle.connect().then( _ => console.log('connect 1')));
kuzzle.connect().then( _ => console.log('connect 2')));

...
```

currently output:
>\> connected
>\> connected
>\> connect 1
>\> reconnected
>\> reconnected
>\> connect 2

## Expected Behavior
expected output:
>\> connected
>\> connect 1
>\> connect 2

## Possible Solution
When calling [`Kuzzle.connect()`](https://github.com/kuzzleio/sdk-javascript/blob/6-dev/src/Kuzzle.js#L237) method, the `connected` state is managed, but not the `connecting` state

This result in double listeners registration, and a force protocol to reconnect without keeping care about previous connection request

**Comment by Aschen** [comment]
Hi @stafyniaksacha,

This behavior is actually fixed with the latest version of the SDK:

```
const {
  Kuzzle,
  WebSocket
} = require('./index');

const kuzzle = new Kuzzle(
  new WebSocket('kuzzle')
);

kuzzle.on('connected', _ => console.log('connected'));
kuzzle.on('reconnected', _ => console.log('reconnected'));

(async () => {
  await kuzzle.connect();
  console.log('connect 1');
  await kuzzle.connect();
  console.log('connect 2');
})()
```
Prints
```
connected
connect 1
connect 2
```
