### ISSUE TITLE
[v6] should return a custom class, and not a raw Error object with injected properties

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/sdk-javascript#361]
Whenever the SDK handles an error response from Kuzzle, it instantiates an `Error` object. Then, a `status` property is injected in it, and the instance is returned to the querying user.

There are a couple problems with this:
- only the status gets injected in the error object ; no other Kuzzle error properties make their way in the object returned to users, thus valuable information can be lost. For instance, the stacktrace (there can be one if Kuzzle runs in dev mode), or the partial array in case of a PartialError error
- this seems wrong to me to "extend" a base class by injecting new properties to its instances, instead of properly inheriting the `Error` object. Also, this means that we cannot document errors properly, and users are left without any information about what they can expect of an error returned by the SDK

Solution: implement a proper KuzzleError class, inheriting the Error one, and copy in it all the properties that can be found in a Kuzzle response `error` property.
And add a documentation for this new class.

**Comment by Aschen** [comment]
https://jira.kaliop.net/browse/KZL-1001
