### ISSUE TITLE
[6.0.0-beta-6] kuzzle.eventActions no longer exists ?

### ISSUE THREAD

**Issue by lethak** [kuzzleio/sdk-javascript#366]
In prior versions, one could do 

```javascript
    const eventList = kuzzle.eventActions

    eventList.forEach((evtName) => {
        kuzzle.addListener(evtName, (arg1, arg2) => {
            console.log('[KUZZLE Event] ' + evtName + ' :: ', arg1, arg2)
        })
    })
```

this was thanks to:

https://github.com/kuzzleio/sdk-javascript/blob/7ac7c1c300be2fa4b18c19c24de1266e5d7c7bae/src/Kuzzle.js#L55

but no longer possible with:

https://github.com/kuzzleio/sdk-javascript/blob/d1f54e26b17151875ba671134348d3f908033dbd/src/Kuzzle.js#L16

May I suggest keeping them public and read only ?
thanks

**Comment by Aschen** [comment]
Hi @lethak !
Yes, this is totally something we can do. Thanks for the feedback :)

**Comment by Aschen** [comment]
https://github.com/kuzzleio/sdk-javascript/pull/367

**Comment by Aschen** [comment]
Won't do for now.  
If someone else need this feature, please comment this issue.
