### ISSUE TITLE
[6-dev] Http protocol do not send query parameters to document.search calls

### ISSUE THREAD

**Issue by thenikso** [kuzzleio/sdk-javascript#371]
When doing a `document.search` call from a Kuzzle instance with an `Http` protocol, the query content is not sent and therefore, the returned hits have no query/filter applied.

## Expected Behavior
The query is sent to the server and returned hits are filter accordingly

## Current Behavior
The returned hits are all the documents in the index/collection as if no filtering got applied

## Possible Solution
It appears as if query/filters parameters are not sent at all in the XHR request. A workaround is to 
use a `WebSocket` protocol instead.

## Steps to Reproduce
```javascript
const kuzzle = new Kuzzle(new Http('localhost'));
await kuzzle.connect();
await kuzzle.document.search('i', 'c', { query: { term: { '_kuzzle_info.author': 'xxx' } } })
// ISSUE: the { query: ... } is not sent to the server
```

## Context (Environment)
I switched to `Http` protocol (from `WebSocket`) to more easily inspect the requests sent by Kuzzle and I noticed that searches were behaving in a different and broken way.

**Comment by Aschen** [comment]
Thanks you for your submission!

**Comment by benoitvidis** [comment]
Hi @thenikso,

Sorry for the late feedback.

Which version of the sdk are you using? 
I tried to reproduce the issue using `6.0.0` and `6.0.0-beta-8` version without any success.

**Comment by thenikso** [comment]
I have now tried with `6.0.0` and it is working. I guess this issue can safely be closed
