### ISSUE TITLE
Perte de connexion

### ISSUE THREAD

**Issue by mehdweb34** [kuzzleio/sdk-javascript#380]
Bonjour,
J'aurais aimé avoir un petit coup de pouce de votre part concernant un petit soucis de perte de connexion. Je dois sûrement mal faire quelque chose :P

**Techno**
Angular 7
SDK kuzzle-javascript

**Cas d'utilisation**
- Je me connecte à mon application via votre sdk et la fonction "kuzzle.auth.login". OK
- Je récupère les infos du user loggé via "kuzzle.auth.getCurrentUser". OK
A savoir que j'essaie d'éviter de "taper" directement dans kuzzle (sans passer par une api)

**Mon problème**
Seulement, lorsque que je rafraichi ma page, je perd la connexion avec Kuzzle, je pense que c'est un comportement normal, mais je n'arrive pas à comprendre comment "récupérer" ma connexion sans repasser par "kuzzle.auth.login" et sans stoker les identifiants de mon user.

Y'aurait-il une âme charitable dans votre équipe qui pourrais m'orienter ?

Merci d'avance

**Comment by Aschen** [comment]
Hello @mehdweb34,
Juste normalement on essaye de rester en anglais pour les échanges sur Github ou autre mais je ferais une exception cette fois :-) 

Le fait que tu perdes la connexion et le JWT est normal quand tu recharges la page puisque ton application Angular est déchargée de la mémoire du navigateur. Toutes les variables déclarées sont donc perdues.

Une solution serait de stocker le token dans le [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), ainsi tu pourrais vérifier si un token existe et si il est valide au lancement de ton application et faire appel à `auth.login` le cas échéant.

**Comment by mehdweb34** [comment]
**_(Sorry for my bad english)_**

Hi @Aschen :)
Thank for your response.

Everything is ok for the recovery of the token and its storage. But I still have a problem to recreate a connection with this token. I can not find a function in the SDK that makes it possible.

**Comment by mehdweb34** [comment]
Hi @Aschen  :)


Everything is corrected on my side. The solution was very simple but was not present in your documentation.

Also, the **"setJwtToken"** function is not present in your Javascript SDK (v6).

Instead, I just had to do:

`// Rebuild the connection from the previously created access token`
`kuzzle.jwt = 'yourToken';`

Thank you.
