### ISSUE TITLE
SDK 6 Http Protocol cause JS engine crash with connect on offline

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/sdk-javascript#418]
I'm building an offline app as PWA.

Doing this while switching network offline or stopping kuzzle server
```ts
const kuzzle = new Kuzzle(new Http(process.env.API_HOST));

try {
   await kuzzle.connect();
 } catch (e) {
   console.log(e);
 }
```

results in `:7512/:1 GET http://localhost:7512/ net::ERR_INTERNET_DISCONNECTED`

will crash the client which is unable to catch the following error thrown by connect.

## Related

- Others methods are immunised, only `connect` seems causing issues.
- Websocket seems immunised.

**Comment by Aschen** [comment]
Hi @ScreamZ ,

Thanks you for your feedback! This will be fixed by this PR: https://github.com/kuzzleio/sdk-javascript/pull/420 (explanation are in the PR description)

**Comment by ScreamZ** [comment]
Closed, resolved by https://github.com/kuzzleio/sdk-javascript/pull/420

**Comment by Kafigueiredo** [comment]
@Aschen when i'm offline, i want to catch an error. This code never resolve: i can't catch this error. 
```js
  try {
    await kuzzle.document.create("xxx", "xxx", xxx);
  } catch (error) {
    console.log(error);
  }
  ```
Chrome console return me : 
```
OPTIONS http://localhost:7512/xxx/xxx/_create net::ERR_INTERNET_DISCONNECTED
```

**Comment by scottinet** [comment]
Hi,

There was a promise-leak occuring on network disconnection, this should be resolved by https://github.com/kuzzleio/sdk-javascript/pull/427

(not yet released on npm)

**Comment by scottinet** [comment]
Hi @Kafigueiredo ,

There was a promise-leak occuring on network disconnection, this should be resolved by https://github.com/kuzzleio/sdk-javascript/pull/427

(not yet released on npm)
