### ISSUE TITLE
Kuzzle connection lost from other functions

### ISSUE THREAD

**Issue by TIB28** [kuzzleio/sdk-javascript#515]
Hello when i connect to kuzzle and login it works fine but when i create a document outside of the function the variable kuzzle.connected is false and i dont think it is the token timeout because it runned just 2 or even less.

Here is my code: 
```
const send_K = async (data) => {
  kuzzle.jwt = kuzzleJwt;
  if(kuzzle.connected) {
    await kuzzle.document.create('device', 'data_device', data);
  } else {
    console.log('Kuzzle is not connected. Trying to reconnect')
    //await init();
    //await kuzzle.document.create('device', 'data_device', data);
  }
}

const init = async () => {
  try {
    await kuzzle.connect();
    kuzzleJwt = await kuzzle.auth.login('local', credentials);
    console.log(kuzzle.connected);
    //setInterval(refresh_token, 6000);
  } catch (error) {
    console.error("Error Kuzzle: ", error);
  } finally {
   kuzzle.disconnect();
  }
};

init();
```

And if i run init() when it is not connected it send error.
The send_K function is called every time it detect a change in a other dbs (or cache)

**Comment by Aschen** [comment]
You are disconnecting the SDK in the `finally` block of the `init` function, so when you call the `send_K` function you are not longer connected.  

Also, Github issues are reserved for bug and features requests. If you have any technical questions you can either ask the community on [Discord](http://join.discord.kuzzle.io/) or the core team on [Stackoverflow](https://stackoverflow.com/search?q=kuzzle) with the `kuzzle` tag
