### ISSUE TITLE
Upgrade to TypeScript v4

### ISSUE THREAD

**Issue by kindlyfire** [kuzzleio/sdk-javascript#549]
## Expected Behavior
SDK should compile on the latest stable version of TypeScript

## Current Behavior
SDK does not compile on TypeScript v4

## Possible Solution
Update TypeScript code to support v4 and update TypeScript dependency in `package.json`
For projects currently using the JS SDK, using TypeScript v3 is a solution until the JS SDK gets an update.

**Comment by scottinet** [comment]
Thanks for noticing. I triaged it so it can be done quickly.
