### ISSUE TITLE
Add keep-alive mechanism to detect connection lost with realtime protocols

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/sdk-javascript#555]
##  Feature Request

We need a keel-alive mechanism built with Kuzzle ping/pong capabilities with the WebSocket protocol to terminate a connection when the connection is lost.

See: https://www.npmjs.com/package/ws#how-to-detect-and-close-broken-connections

**Comment by Yoann-Abbes** [comment]
Related: https://github.com/kuzzleio/sdk-javascript/issues/277
