### ISSUE TITLE
Add a param that describe the origin of the disconnect event

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/sdk-javascript#638]
## Feature Description

Add a param to `disconnect` event that specify if the disconnection is forced (like login/logout with cookieAuth) or not.

## Example Use Case

On my web application, I'm displaying a toast that specify the app is offline when I receive the `disconnect` event from the sdk.
I don't want to show that toast when the disconnection is initiated by the sdk because of cookieAuth login/logout.

**Comment by Shiranuit** [comment]
We could be more specific and add an `origin` parameter that help us determine what is causing the disconnection.
With that we could have something like that:
`websocket/auth-renewal`
`network/connection-lost`
`sdk/manual-disconnection`
