### ISSUE TITLE
`jwtTokenExpired` event on `logout` action

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/sdk-javascript#68]
Does it make sense to trigger the event after a `logout` action? Like, my token is expired (so I'm logged out) and I try to logout, so I get the event although logging out of an expired session results in a successful logout. IMHO the event is redundant in this case.

A real-life case (in the BackOffice) is
* My token is expired
* I click on the Logout button
* I both see the login page and the login modal

**Comment by scottinet** [comment]
You're right, it does not make sense.

I'm submitting a PR to make the SDK ignore token expiration responses from Kuzzle if they come from a `logout` query.

**Comment by benoitvidis** [comment]
What if the application is a multi-device one and the user logs out on one of them only? Do all clients recieve the logout event notification?

**Comment by scottinet** [comment]
It's unrelated to the current issue, but you're right: currently, the `logout` API route invalidate only the provided token, instead of logging out the user and all his associated tokens.
I'll write submit the subject to our weekly conception workshop.
