### ISSUE TITLE
HTTP protocol should call publicApi after authentication to retreive API routes

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/sdk-javascript#691]
## Feature Description

The [server:publicApi](https://docs.kuzzle.io/core/2/api/controllers/server/public-api/) action allows to retrieve HTTP routes corresponding to API actions. The HTTP protocol is using this action to retrieve application custom routes (from app or plugins) and then send requests to corresponding HTTP routes with correct verbs.

This action can be restricted to anonymous user and thus the HTTP protocol will not work.

After authentication, the protocol should try again to retrieve the routes through `server:publicApi`

**Comment by rolljee** [comment]
Followed on JIRA
