### ISSUE TITLE
Add strong typing on the `query` method

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/sdk-javascript#706]
## Feature Description

In order to comply with interfaces contracts defined as types, we need to add optional strong typing to the `query` method.

Each controller action should define it's own contract with 2 interfaces:
 - `ControllerActionRequest`
 - `ControllerActionResult`

Then those types can be used with the `query` method to ensure contracts are validated.

```
export interface NotificationSmsRequest extends RequestPayload {
  controller: 'notification',
  action: 'sms',
  engineId: string;
  body: {
    smsContent: string;
  }
};

interface NotificationSmsResult {
    smsCount: number;
}

const { result } = await sdk.query<NotificationSmsRequest, NotificationSmsResult>({
  controller: 'notification',
  action: 'sms',
  engineId: 'tenant-worksite-kuzzle',
  body: {
    smsContent: 'Hello, world',
  }
});

result.smsCount; // number
```

**Comment by OlivierCavadenti** [comment]
Solve by https://github.com/kuzzleio/sdk-javascript/pull/707
