### ISSUE TITLE
npm compatibility?

### ISSUE THREAD

**Issue by Rajan** [kuzzleio/sdk-javascript#89]
RethinkDB is the only real-time database solution that comes to my mind.
Is it possible to add npm modules for extra functionality? how db connections work?

**Comment by j33f** [comment]
This SDK allow you to connect to your Kuzzle server and facilitate calls to its API. It is not made to connect to something else directly.

If you need to extend the Kuzzle functionalities, you can create a plugin for it, not for the SDK.
